config/routes.rb
Rails.application.routes.draw do

  get 'contact_form/new'

  get 'contact_form/create'

	root 'trips#index'
	devise_for :users, :controllers => {:registrations => "my_devise/registrations"}

	get '/users', to: 'users#show'
  get '/users/:id/postulaciones', to: 'users#postulaciones'
  get '/users/:id/showMisViajes', to: 'trips#showMisViajes'
  get '/ayuda', to: 'static_pages#ayuda'

  resources :trips, only: [] do
    resources :questions do
      resources :answers
    end
  end
  resources :contact_forms, only: [:new, :create]
	resources :users do
    collection do
      get :pagar
      put :pagarTodoSaldo
      put :pagarTodoTarjeta
      put :pagarViajeSaldo
      put :pagarViajeTarjeta
    end
    resources :accounts, only: [:index]
    resources :trips do
      member do
        put :aceptar
        put :rechazar
        put :postularse
        delete :cancelarPostulacion
        delete :eliminar
      end
    end
    resources :scores, only: [:edit, :update]
    member do
      get 'calificaciones', to: 'scores#showCalificaciones'
      get 'calificaciones_pendientes', to: 'scores#showCalifARealizar'
    end
		resources :vehicles
  end

end

app/views/partials/partialsTrips/_allTrips.html.erb
 <div class="row">
  <h1 style="text-align: center;">
    Viajes disponibles
  </h1>
  <div class="col-md-1"></div>
    <div class="col-md-10">
      <% if @trips.empty? %>
        <% if user_signed_in? %>
          <h3 style="text-align: center;">
            No hay viajes,  <%= link_to ' crea uno!', new_user_trip_path(@user) %>
          </h3>
        <% else %>
          <h3 style="text-align: center;">
            No hay viajes,  <%= link_to ' inicia sesion', new_user_session_path %> para crear uno!
          </h3>
        <% end %>
      <% else %>
        <div class="centering", style="margin-bottom: 10px; margin-top: 5px; background-color: #BDEDBA; text-align: center; font-size:16px">
          <b>Ordenar por: </b>
          <%= sort_link(@q, :origen, ['origen', 'destino'], 'Origen y destino') %> |
          <%= sort_link(@q, :destino)%> |
          <%= sort_link(@q, :fecha_inicio, ['fecha_inicio', 'hora_inicio'], 'Fecha') %>
        </div>
        <% @trips.each do |t| %>
          <div style="align-content: center;">
            <div class="well my-jumbotron">
              <div class="row">
                <h3 style="text-align: center;">
                  <%='Origen: '+t.origen %>   -    <%= 'Destino: '+t.destino %>
                </h3>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <h5>
                    <b>Fecha: </b> <%= formato_fecha(t.fecha_inicio) %>
                  </h5>
                  <h5>
                    <b>Hora: </b> <%= t.hora_inicio.strftime('%H:%M') %>
                  </h5>
                  <h5>
                      <b>Periodico: </b>
                      <% if t.periodics.any? %>
                        Si
                      <% else %>
                        No
                      <% end %>
                  </h5>
                  <h5>
                    <b>Piloto: </b> <%= link_to image_tag(t.piloto.avatar.url,:class=>"circular-image small-image")+'  '+usernameOf(t.piloto), user_path(t.piloto) %>
                  </h5>
                  <h5>
                    <b>Asientos: </b> <%= t.cantidad_asientos_ocupados %> / <%= t.vehicle.cantidad_asientos %>
                  </h5>
                </div>
                <div class="col-md-8">
                  <div class="row" style="width: 100%;">
                    <h4>
                      <b>Descripcion:</b> <%= t.descripcion %>
                    </h4>
                  </div>
                </div>
              </div>
              <div class="center" style="width: 100%">
                <b>
                  <%= link_to 'Ver viaje', user_trip_path(t.piloto, t),:class => "btn btn-block btn-md my-button-color my-link-button"%>
                </b>
              </div>
            </div>
            <br>
          </div>
        <% end %>
      <% end %>
      <div class="pagination-wrapper">
        <div class="pagination">
          <%= will_paginate @trips, previous_label: 'Página anterior', next_label: 'Página siguiente' %>
        </div>
      </div>
    </div>
  <div class="col-md-1"></div>
</div>

app/views/partials/partialsTrips/_showTripsAcept.html.erb
<div class="row">
	<div class="well my-jumbotron-green">
		<% aceptados = Embarkment.where(estado: 'a', trip_id: @trip).all %>
		<% if aceptados.empty? %>
			<div style="text-align: center; font-size: 18px">
			<b>No se ha aceptado a nadie en este viaje.</b>
			</div>
		<% else %>
			<% aceptados.each do |ace| %>
				<% usr = User.find(ace.user_id) %>
				<% if current_user == @trip.piloto %>
					<div class="well my-jumbotron2">
						<div class="row">
							<div class="col-md-3">
								<div style="float: left; font-size: 18px;">
									<%= image_tag(usr.avatar,:class=>"circular-image", :alt=>'Avatar', size: '50x50')%>
									<%= link_to usernameOf(usr), user_path(usr) %><br>
								</div>
							</div>
							<div class="col-md-2">
								<br>
								<b>Reputacion  <%= image_tag('pasajeris.png', size: '20x20', class: 'logitos') %>:</b> <%= usr.calificacionCopiloto %>
							</div>
							<div class="col-md-5">
								<b>Nombre:</b>
								<%= usr.nombre + ' ' + usr.apellido %><br>
								<b>Telefono:</b>
								<% if usr.telefono %>
									<%= usr.telefono %>
								<% else %>
									El usuario no tiene numero de telefono.
								<% end %><br>
								<b>Email:</b>
								<%= usr.email %><br>
							</div>
							<div class="col-md-2">
								<div class="boton-ace-rec" style="margin-top: 10px">
									<%= button_to "Eliminar", {controller: :trips,
																					 action: 'eliminar',
																					 idU: usr.id,
																					 idT: @trip.id},
																					 {class: 'btn btn-danger',
																					 method: :delete} %>
								</div>
							</div>
						</div>
						<div style="clear:both;">
						</div>
					</div>
				<% elsif usr == current_user %>
					<div class="well-sm my-jumbotron2">
						<div style="float: left; font-size: 18px;">
							<%= image_tag(usr.avatar,:class=>"circular-image post-image", :alt=>'Avatar')%>
							<%= link_to usernameOf(usr), user_path(usr) %>
						</div>
						<div class="boton-ace-rec">
							<%= button_to "Cancelar postulacion", {controller: :trips,
																			 action: 'cancelarPostulacion',
																			 idU: current_user,
																			 idT: @trip.id,},
																			 {class: 'btn btn-danger',
																			 method: :delete,
																			 data: {confirm: '¿Estas seguro que queres cancelar la postulacion? Se te restara un punto de calificacion como acompañante.'}}
																				%>
						</div>
						<div style="clear:both;">
						</div>
					</div>
				<% else %>
					<div class="well-sm my-jumbotron2">
						<div style="font-size: 18px;">
							<%= link_to image_tag(usr.avatar,:class=>"circular-image post-image", :alt=>'Avatar')+' '+usernameOf(usr), user_path(usr)%>
						</div>
					</div>
				<% end %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/partials/partialsTrips/_showTripsInfo.html.erb
<% v = Vehicle.find(@trip.vehicle_id) %>
<div class="row">
<div class="well my-jumbotron">
	<div style="text-align: center;">
		<h2>
			<% if @trip.origen != nil %>
        		<%= @trip.origen %>
    		<% else %>
        		no especifico origen
    		<% end %>
    		 - <%= @trip.destino %>
    	</h2>
    	<h2>  <br>  </h2>
	</div>
	<div class="row">
		<div class="col-md-6">
			<h4><b> Informacion general </b></h4>
			<br>
			<div class="row">
				<div class=" col-md-6">
					<b>Origen: </b>
	        			<%= @trip.origen %> <br>
	    		</div>
	    		<div class="col-md-6">
					<b>Destino:</b>
						<%= @trip.destino %> <br>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-6">
					<% if !@trip.periodics.empty? %>
						<b>Fechas de salida:</b><br>
						<%= formato_fecha(@trip.fecha_inicio) %><br>
						<% @trip.periodics.each do |t| %>
							<%= formato_fecha(t.fecha) %> <br>
						<% end %>
					<% else %>
						<b>Fecha de salida:</b>
						<%= formato_fecha(@trip.fecha_inicio) %> <br>
					<% end %>
				</div>
				<div class="col-md-6">
					<b>Hora de salida:</b>
						<%= @trip.hora_inicio.strftime('%H:%M') %> <br>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-6">
					<b>Piloto:</b>
						<%= link_to image_tag(@trip.piloto.avatar.url,:class=>"circular-image small-image")+'  '+usernameOf(@trip.piloto), user_path(@trip.piloto) %> <br>
				</div>
				<div class="col-md-6">
					<b>Reputacion <%= image_tag('autis.png', size: '23x23', class: 'logitos') %>:</b>
						<%= @trip.piloto.calificacionPiloto %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-6">
					<b>Asientos ocupados:</b>
							<%= @trip.cantidad_asientos_ocupados %>/<%= v.cantidad_asientos %><br>
				</div>
				<div class="col-md-6"><b> Duración: </b><%= @trip.duracion %>hs </div>
			</div>
			<br>



			<!-- Aca puse que el piloto no vea su propia informacion de contacto o de ultima no vea el "Contacto del piloto" y ademas la impresion de datos para un usuario ya aceptado, le falta el estilo-->
			<% unless @trip.piloto == current_user %>
				<b>Contacto del Piloto: </b><br>
				<% aceptados = Embarkment.where(estado: 'a', trip_id: @trip).all %>
				<% if aceptados.exists?(user_id: current_user) %>
					<%= @trip.piloto.nombre + ' ' + @trip.piloto.apellido %><br>
					<% if @trip.piloto.telefono %>
	          			<%= @trip.piloto.telefono %><br>
	        		<% else %>
	          			El piloto no tiene numero de telefono.<br>
	        		<% end %>
	        		<%= @trip.piloto.email %><br>
				<% else %>
					Solo los usuarios aceptados como copiloto pueden ver esta informacion
				<% end %>
			<% end %>
			<!-- -->



		</div>
		<div class="col-md-6">
			<h4><b>Costo total:</b> $<%= (@trip.costo).round(2) %> <br></h4>
				(el costo por persona será calculado cuando el viaje sea realizado, un estimativo es: $<%= (@trip.costo/v.cantidad_asientos).round(2) %> por persona)<br><br>
			<div class="col-md-2">
			</div>
			<div class="col-md-8">
			<div class="well my-jumbotron2">
			<h4><b>Vehiculo:</b></h4>
				<div class="row">
					<div class="col-md-6">
						<b>Patente:</b> <%= v.patente %><br>
						<b>Marca:</b> <%= v.marca %> <br>
						<b>Tipo:</b> <%= v.tipo %> <br>
						<b>Color:</b> <%= v.color %> <br>
					</div>
					<div class="col-md-6">
						<br>
						<b>Modelo:</b> <%= v.sub_marca %> <br>
						<b>Año:</b> <%= v.modelo %> <br>
						<b>Asientos:</b> <%= v.cantidad_asientos %>
					</div>
				</div>
			</div>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
	<br>
	<h4><b>Descripcion del Viaje:</b></h4>
	<div class="well my-jumbotron2">

		<%= @trip.descripcion %>
	</div>
	<br>
	<div class="row">
		<% if user_signed_in? && !@trip.postulantes.exists?(id: current_user) &&
			@trip.piloto != current_user%>
			<%= button_to 'Postularse', {controller: :trips, action: 'postularse', idT: @trip.id},
                {class: "btn btn-lg colapso btn-block my-link-button", method: :put} %>
		<% end %>
		<% if current_user == @trip.piloto %>
			<div class="col-md-1"></div>
			<div class="col-md-4">
				<b>
		  			<%= link_to 'Modificar', edit_user_trip_path(@trip.piloto, @trip),:class => "btn btn-block btn-md my-button-color my-link-button"%>
				</b>
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				<b>
					<%= link_to 'Eliminar',{controller: :trips, action: :destroy, idT: @trip.id}, {data: {confirm: "Se te cobrara el 5\% del costo del viaje y se te restara un punto a tu reputación como piloto por cada usuario aceptado en el viaje. ¿Estas seguro que deseas continuar? "}, method: :delete, :class => "btn btn-block btn-md my-button-color my-link-button"} %>
				</b>
			</div>
			<div class="col-md-1"></div>
		<% end %>
	</div>
</div>
</div>

app/views/partials/partialsTrips/_showTripsPostul.html.erb
<div class="row">
  <div class="well my-jumbotron-blue">
    <% pendientes = Embarkment.where(estado: 'p', trip_id: @trip).all %>
    <% if pendientes.empty? %>
      <div style="text-align: center; font-size: 18px">
        <b>No hay postulantes para este viaje!</b>
      </div>
    <% else %>
      <% pendientes.each do |emb| %>
        <% usr = User.find(emb.user_id) %>
        <div class="well-sm my-jumbotron2">
          <div class="row">
            <div class="col-md-3">
              <div style="float: left;font-size: 18px;">
                <%= image_tag(usr.avatar,:class=>"circular-image post-image", :alt=>'Avatar')%>
                <%= link_to usernameOf(usr), user_path(usr) %>
              </div>
            </div>
            <div class="col-md-4">
              <div style="margin-top: 6px">
              <b>Reputacion  <%= image_tag('pasajeris.png', size: '20x20', class: 'logitos') %>:</b> <%= usr.calificacionCopiloto %>
            </div>
            </div>
            <div class="col-md-5">
              <% if current_user == @trip.piloto %>
                <div class="boton-ace-rec">
                  <%= button_to "Rechazar", {controller: :trips,
                                            action: 'rechazar',
                                            idU: usr.id,
                                            idT: @trip.id},
                                            {class: 'btn btn-danger',
                                            method: :put} %>
                </div>
                <div class="boton-ace-rec">
                  <%= button_to "Aceptar", {controller: :trips,
                                           action: 'aceptar',
                                           idU: usr.id,
                                           idT: @trip.id},
                                           {class: 'btn btn-success',
                                           method: :put} %>
                </div>
                <div style="clear:both;">
                </div>
              <% elsif current_user == usr %>
                <div class="boton-ace-rec">
                  <%= button_to "Cancelar postulacion", {controller: :trips,
                                                        action: 'cancelarPostulacion',
                                                        idU: current_user.id,
                                                        idT: @trip.id},
                                                        {class: 'btn btn-danger',
                                                        method: :delete} %>
                </div>
                <div style="clear:both;">
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/partials/partialsTrips/_showTripsPreg.html.erb
<div class="row">
	<div class="well my-jumbotron">
		<% if @trip.questions.empty? %>
			<div style="text-align: center; font-size: 18px">
				<b>No hay Preguntas al viaje</b>
			</div>
		<% else %>
			<% @trip.questions.each do |q| %>
				<div class="media well-sm my-jumbotron2">
					<!-- PREGUNTA EXISTENTE AL VIAJE -->
					<div class="media-left">
						<%= image_tag(q.comentador.avatar,:class=>"circular-image post-image", :alt=>'Avatar')%>
					</div>
					<div class="media-body">
						<h4 class="media-heading"> <%= link_to usernameOf(q.comentador), user_path(q.comentador) %>
							<small><i> <span class="glyphicon glyphicon-calendar"></span>
								<% fechaQ = q.created_at - 10800 %>
								<%= '  '+formato_fecha(fechaQ.to_date) %>  <%= fechaQ.to_time.strftime('%H:%M') %>
							</i></small>
						</h4>
						<p> <%= q.pregunta %> </p>
						<% if !q.answer %>
							<% if current_user == @trip.piloto %>
								<!-- SI NO TIENE RESPUESTA EL LUGAR PARA OFRECER RESPONDER -->
								<%= form_for([@trip, q, @answer]) do |a| %>
									<div class="form-group">
										<%= a.label :respuesta %> <br>
										<%= a.text_area :respuesta, class: "form-control" %>
									</div>
									<div class=" actions">
										<%= a.submit "Responder", class:"btn my-link-button my-button-color" %>
									</div>
								<% end %>
							<% end %>
						<% else %>
							<div class="media well-sm my-jumbotron2">
								<!-- SI TIENE RESPUESTA LA RESPUESTA A LA PREGUNTA -->
								<div class="media-left">
									<%= image_tag(@trip.piloto.avatar,:class=>"circular-image post-image", :alt=>'Avatar')%>
								</div>
								<div class="media-body">
									<h4 class="media-heading"> <%= link_to usernameOf(@trip.piloto), user_path(@trip.piloto) %>
										<small><i><span class="glyphicon glyphicon-calendar"></span>
											<% fechaA = q.answer.created_at - 10800 %>
											<%= '  '+formato_fecha(fechaA.to_date) %>  <%= fechaA.to_time.strftime('%H:%M') %>
										</i></small>
									</h4>
									<p> <%= q.answer.respuesta %> </p>
								</div>

							</div>
						<% end %>
					</div>
				</div>
			<% end %>
		<% end %>

		<% if current_user != @trip.piloto %>
		<br><br>
			<div class="row">
				<!-- <div class="col-md-1"></div> -->
				<div class="col-md-12">
					<% if user_signed_in? %>
						<div >
							<%= form_for([@trip, @question]) do |q| %>
								<div class="form-group">
									<%= q.label :pregunta %> <br>
									<%= q.text_area :pregunta, class: "form-control" %>
								</div>
								<div class=" actions">
									<%= q.submit "Realizar pregunta", class:"btn my-link-button my-button-color" %>
								</div>
							<% end %>
						</div>
					<br>
					<% end %>
				</div>
				<!-- <div class="col-md-1"></div> -->
			</div>
		<% end %>	
	</div>
</div>