config/routes.rb
Rails.application.routes.draw do

  get 'contact_form/new'

  get 'contact_form/create'

	root 'trips#index'
	devise_for :users, :controllers => {:registrations => "my_devise/registrations"}

	get '/users', to: 'users#show'
  get '/users/:id/postulaciones', to: 'users#postulaciones'
  get '/users/:id/showMisViajes', to: 'trips#showMisViajes'
  get '/ayuda', to: 'static_pages#ayuda'

  resources :trips, only: [] do
    resources :questions do
      resources :answers
    end
  end
  resources :contact_forms, only: [:new, :create]
	resources :users do
    collection do
      get :pagar
      put :pagarTodoSaldo
      put :pagarTodoTarjeta
      put :pagarViajeSaldo
      put :pagarViajeTarjeta
    end
    resources :accounts, only: [:index]
    resources :trips do
      member do
        put :aceptar
        put :rechazar
        put :postularse
        delete :cancelarPostulacion
        delete :eliminar
      end
    end
    resources :scores, only: [:edit, :update]
    member do
      get 'calificaciones', to: 'scores#showCalificaciones'
      get 'calificaciones_pendientes', to: 'scores#showCalifARealizar'
    end
		resources :vehicles
  end

end

app/views/partials/_footer.html.erb
<footer class="footer">
	<nav>
	 <ul>
		  <copyright class="copy"> Un Aventon! &copy;</copyright>
		  <li> <%= link_to 'Contacto', new_contact_form_path %></li>
		  <li> <%= link_to 'Ayuda', ayuda_path %></li>
	 </ul>
	</nav>
</footer>

app/views/partials/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <%= link_to image_tag('Logo.jpg',:class=>"circular-image", :alt=>'Un Aventon!', size: '50x50'), root_path %>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-center nav-btn">
          <li class="my-button"><%= link_to 'Crear Viaje', new_user_trip_path(current_user), class: "navbutton" %></li>

        </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right my-navbar">
        <li><%= link_to "Inicio", root_path %></li>
        <% if user_signed_in? %>
            <li> <%= link_to image_tag(current_user.avatar.url,:class=>"circular-image small-image")+'  '+current_user.email.split('@').first, current_user %></li>
            <li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Crear cuenta', new_user_registration_path %></li>
          <li><%= link_to 'Iniciar sesión', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/partials/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>