config/routes.rb
Rails.application.routes.draw do

  get 'contact_form/new'

  get 'contact_form/create'

	root 'trips#index'
	devise_for :users, :controllers => {:registrations => "my_devise/registrations"}

	get '/users', to: 'users#show'
  get '/users/:id/postulaciones', to: 'users#postulaciones'
  get '/users/:id/showMisViajes', to: 'trips#showMisViajes'
  get '/ayuda', to: 'static_pages#ayuda'

  resources :trips, only: [] do
    resources :questions do
      resources :answers
    end
  end
  resources :contact_forms, only: [:new, :create]
	resources :users do
    collection do
      get :pagar
      put :pagarTodoSaldo
      put :pagarTodoTarjeta
      put :pagarViajeSaldo
      put :pagarViajeTarjeta
    end
    resources :accounts, only: [:index]
    resources :trips do
      member do
        put :aceptar
        put :rechazar
        put :postularse
        delete :cancelarPostulacion
        delete :eliminar
      end
    end
    resources :scores, only: [:edit, :update]
    member do
      get 'calificaciones', to: 'scores#showCalificaciones'
      get 'calificaciones_pendientes', to: 'scores#showCalifARealizar'
    end
		resources :vehicles
  end

end

app/views/partials/partialsUser/_botonesPerfil.html.erb
<% if @user == current_user %>
  <%= link_to 'Mi Perfil',users_path,:class => "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Mis Viajes', {controller: :trips, action: 'showMisViajes', id: @user.id}, class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Mis Vehiculos', user_vehicles_path(@user), class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Mis Postulaciones', '/users/'+@user.id.to_s+'/postulaciones', class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Mis Calificaciones', {controller: :scores, action: 'showCalificaciones', id: @user.id}, class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Calificaciones Pendientes', {controller: :scores, action: 'showCalifARealizar', id: @user.id}, class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Editar Perfil', edit_user_registration_path, class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Cuenta', user_accounts_path(@user), class: "btn btn-block btn-sm my-button-color my-link-button" %>
<% else %>
  <br><br>
  <%= link_to 'Perfil', users_path,:class => "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Viajes', {controller: :trips, action: 'showMisViajes', id: @user.id}, class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Calificaciones',  {controller: :scores, action: 'showCalificaciones', id: @user.id}, class: "btn btn-block btn-sm my-button-color my-link-button" %>
  <%= link_to 'Vehiculos', user_vehicles_path(@user), class: "btn btn-block btn-sm my-button-color my-link-button" %>
<% end %>

app/views/partials/partialsUser/_botonesPerfilNav.html.erb
<ul class="nav nav-pills nav-stacked nav-pills-perf" id="myDIV">
	<% if @user == current_user %>
		<li class="pri"> <%= link_to 'Mi Perfil',user_path(@user),:class => "aperf" %> </li>
		<li><%= link_to 'Mis Viajes', {controller: :trips, action: 'showMisViajes', id: @user.id},:class => "aperf" %></li>  
		<li><%= link_to 'Mis Vehiculos', user_vehicles_path(@user),:class => "aperf" %></li>
		<li><%= link_to 'Mis Postulaciones', '/users/'+@user.id.to_s+'/postulaciones',:class => "aperf" %></li>
		<li><%= link_to 'Mis Calificaciones', {controller: :scores, action: 'showCalificaciones', id: @user.id},:class => "aperf" %></li>
		<li><%= link_to 'Calificaciones Pendientes', {controller: :scores, action: 'showCalifARealizar', id: @user.id},:class => "aperf" %></li>
		<li><%= link_to 'Mi Cuenta', user_accounts_path(@user),:class => "aperf" %></li>
		<li><%= link_to 'Editar Perfil', edit_user_registration_path,:class => "aperf" %></li>
	<% else %>
		<br><br>
		<li><%= link_to 'Perfil', user_path(@user),:class => "aperf" %></li>
		<li><%= link_to 'Viajes', {controller: :trips, action: 'showMisViajes', id: @user.id},:class => "aperf" %></li>  
		<li><%= link_to 'Calificaciones',  {controller: :scores, action: 'showCalificaciones', id: @user.id},:class => "aperf" %></li>
		<li><%= link_to 'Vehiculos', user_vehicles_path(@user),:class => "aperf" %></li>
	<% end %>
</ul>
<script>
	$(document).ready(function () {
  		$(".nav li").removeClass("active");
  		$('a[href="' + this.location.pathname + '"]').parents('li,ul').addClass('active');
  		if(! $('ul li').hasClass('active')){
  			$('ul li').first().addClass('active');
  		}
  	});
</script>

app/views/partials/partialsUser/_botonesPerfilVehiculo.html.erb
<% if @user == current_user %>
  <%= link_to 'Nuevo Vehiculo', new_user_vehicle_path(@user),:class => "btn btn-block btn-sm colapso my-link-button" %>
<% end %>

app/views/partials/partialsUser/_deudaCopiloto.html.erb
<% if @deuda_copiloto.empty? %>
	<h3>No posee deudas a pilotos de los viajes que ha realizado</h3>
<% else %>
	<% @deuda_copiloto.each do |deuda| %>
		<div class="well my-jumbotron">
			<div class="row">
	 			<div class=" col-md-9">
	 				<div class="row">
	 					<div class="col-md-8">
	 					<h4> <b> <%= link_to deuda.trip.origen+'  -  '+deuda.trip.destino, user_trip_path(deuda.trip.piloto, deuda.trip) %> </b> </h4>
	 					</div>
	 					<div class="col-md-4">
						<h5> <span class="glyphicon glyphicon-calendar"></span> <%= '  '+formato_fecha(deuda.trip.fecha_inicio) %>  <%= deuda.trip.hora_inicio.strftime('%H:%M') %> </h5>
	 					</div>
	 				</div>
	 				<div class="row">
	 					<div class="col-md-8">
	 						<b>Piloto: </b> <%= link_to image_tag(deuda.trip.piloto.avatar,:class=>"circular-image post-image", :alt=>'Avatar')+'  '+ usernameOf(deuda.trip.piloto), user_path(deuda.trip.piloto) %>
	 					</div>
	 					<div class="col-md-4" style="margin-top: 6px">
	 						<b> Deuda: </b> $ <%= deuda.deuda %>
	 					</div>
	 				</div>
	 			</div>
	 			<div class="col-md-3" style="margin-top: 15px">
	 				<%= link_to 'Pagar', pagar_users_path(id: @user, idT: deuda.trip, tipo: 'c') , {class: "btn btn-block btn-sm colapso my-link-button"} %>
	 			</div>
	 		</div>
		</div>
	<% end %>
<% end %>
 

app/views/partials/partialsUser/_deudaPiloto.html.erb
<% if @deuda_piloto.empty? %>
	<h3>No posee deudas de viajes que ha creado</h3>
<% else %>
	<% @deuda_piloto.each do |deuda| %>
		<div class="well my-jumbotron">
			<div class="row">
	 			<div class=" col-md-9">
	 				<div class="row">
	 					<div class="col-md-8">
	 					<h4> <b> <%= link_to deuda.origen+'  -  '+deuda.destino, user_trip_path(deuda.piloto, deuda) %> </b> </h4>
	 					</div>
	 					<div class="col-md-4">
	 					<h5> <span class="glyphicon glyphicon-calendar"></span> <%= '  '+formato_fecha(deuda.fecha_inicio) %>  <%= deuda.hora_inicio.strftime('%H:%M') %> </h5>

	 					</div>
	 				</div>
	 				<div class="row">
	 					<div class="col-md-8">
	 						<b>Piloto: </b> <%= link_to image_tag(deuda.piloto.avatar,:class=>"circular-image post-image", :alt=>'Avatar')+'  '+ usernameOf(deuda.piloto), user_path(deuda.piloto) %>
	 					</div>
	 					<div class="col-md-4" style="margin-top: 6px">
	 						<% debe_app = (deuda.costo * 0.05).round(2) %>
	 						<b> Deuda: </b> $ <%= debe_app %>
	 					</div>
	 				</div>
	 			</div>
	 			<div class="col-md-3" style="margin-top: 15px">
	 				<%= link_to 'Pagar', pagar_users_path(id: @user, idT: deuda, tipo: 'p') , {class: "btn btn-block btn-sm colapso my-link-button"} %>
	 			</div>
	 		</div>
		</div>
	<% end %>
<% end %>
 

app/views/partials/partialsUser/_misViajesRealizados.html.erb
<div class="row">
	<div class="col-md-12">
		<br>
		<%if @realizado.empty? %>
			<div>
				<h4> No hay viajes realizados </h4>
			</div>
		<% else %>
			<% @realizado.each do |t| %>
			<div class="well my-jumbotron">
				<div class="row">
					<h3 style="text-align: center;">
					  <%='Origen: '+t.origen %>   -    <%= 'Destino: '+t.destino %>
					</h3>
				</div>
				<div class="row">
					<div class="col-md-4">
					  <h5>
						<b>Fecha: </b> <%= formato_fecha(t.fecha_inicio) %>
					  </h5>
					  <h5>
						<b>Hora: </b> <%= t.hora_inicio.strftime('%H:%M') %>
					  </h5>
					  <h5>
	                      <b>Periodico: </b>
	                      <% if t.periodics.any? %>
	                        Si
	                      <% else %>
	                        No
	                      <% end %>
                  	  </h5>
					  <h5>
						<b>Piloto: </b> <%= link_to image_tag(t.piloto.avatar.url,:class=>"circular-image small-image")+'  '+usernameOf(t.piloto), user_path(t.piloto) %>
					  </h5>
					  <h5>
						<b>Asientos: </b> <%= t.cantidad_asientos_ocupados %> / <%= t.vehicle.cantidad_asientos %>
					  </h5>
					</div>
					<div class="col-md-8">
					  <div class="row" style="width: 100%;">
						<h4>
						  <b>Descripcion:</b> <%= t.descripcion %>
						</h4>
					  </div>
					</div>
				</div>
				<br>
				<div class=" row">
					<div class="col-md-4"></div>
					<div class="col-md-4">
						<b>
							<%= link_to 'Ver detalle', user_trip_path(t.piloto, t),:class => "btn btn-block btn-md my-button-color my-link-button"%>
						</b>
					</div>
					<div class="col-md-4"></div>
				</div>
			</div>
			<br>
			<% end %>
		<% end %>
		<div class="pagination-wrapper">
		<div class="pagination">
		  <%= will_paginate @realizado, param_name: 'rea_page', previous_label: 'Página anterior', next_label: 'Página siguiente' %>
		</div>
	  </div>
	</div>
</div>

app/views/partials/partialsUser/_mostrarCalificacionesPendientes.html.erb
<br>
<div class="row">
	<div class="col-md-1">
	</div>
	<div class="col-md-10">
		<% if @calification.empty? %>
			<h4 style="text-align: center;"> No debe calificaciones a otros usuarios. </h4>
		<% else %>
			<% @calification.each do |calif| %>
			 	<div class="well-sm my-jumbotron">
			 		<div class="row">
			 			<div class=" col-md-9">
			 			<% if calif.tipo_calificacion == 'p' %>
			 				<b>Piloto: </b>
			 			<% else %>
			 				<b> Copiloto: </b>
			 			<% end %>
			 			<%= link_to image_tag(calif.calificado.avatar,:class=>"circular-image post-image", :alt=>'Avatar')+'  '+ usernameOf(calif.calificado), user_path(calif.calificado) %><br>
			 			</div>
			 			<div class="col-md-3">
			 			<%= link_to 'Calificar', edit_user_score_path(current_user, calif), :class => "btn btn-block btn-sm colapso my-link-button" %>
			 			</div>
			 		</div>
			 	</div>
			 	<br>
			<% end %>
		<% end %>
		<div class="pagination-wrapper">
        	<div class="pagination">
          		<%= will_paginate @calification, previous_label: 'Página anterior', next_label: 'Página siguiente' %>
        	</div>
      	</div>
	</div>
	<div class="col-md-1">
	</div>
</div>

app/views/partials/partialsUser/_mostrarCalificacionesPropiasCopiloto.html.erb
<br>
<div class=" row">
	<div class="col-md-6">
		<h4 style="text-align: left; margin-left: 15px"> Reputacion:  <%= image_tag('pasajeris.png', size: '18x18', class: 'logitos') %> <%= @user.calificacionCopiloto %> </h4><br>
  	</div>
	<div class="col-md-6">
		<h4 style="text-align: right; margin-right: 15px"> Calificaciones: <%= @calif_copiloto.size %><br></h4>
	</div>
</div>
<br>

<% if @calif_copiloto.empty? %>
	<h4 style="text-align: center"> Aun no posee calificaciones como copiloto. </h4>
<% else %>
	<% @calif_copiloto.each do |calif| %>
	 	<% if calif.calificacion >0 %>
		 	<div class="well-sm post-acept">
			 	<div class="row">
			 		<div class="col-md-12">
			 			<div class="row">
				 			<div class="col-md-1">
				 				<div style="text-align: left; margin-left: 15px"> 
						 			<span class="glyphicon glyphicon-circle-arrow-up green-glyph"></span>
						 		</div>
						 	</div>
						 	<div class="col-md-8">
						 		<b>Creador: </b>
						 		<% if !calif.creador %>
						 			<b>UnAventon!<span class="glyphicon glyphicon-copyright-mark"></span></b> <br>
						 		<% else %>
						 			 <%= link_to image_tag(calif.creador.avatar,:class=>"circular-image post-image", :alt=>'Avatar')+'  '+ usernameOf(calif.creador), user_path(calif.creador) %><br>
						 		<% end %>
				 			</div>
				 			<div class="col-md-3"> 
				 				<div style="text-align: right; margin-right: 15px" >
				 					<span class="glyphicon glyphicon-calendar"></span>  <%= '  '+formato_fecha(calif.fecha) %> 
				 					<%= calif.hora.strftime('%H:%M') %><br>
				 				</div>
				 			</div>
			 			</div>
			 			<br>
			 			<div class="row" style="margin-right: 15px; margin-left:15px ">
					 			<b>Descripcion: </b><br>
					 			<div class="well my-jumbotron2">
					 				<%= calif.descripcion %>
					 			</div>
			 			</div>
			 		</div>
			 	</div>
			</div>
		<% elsif calif.calificacion < 0 %>
			<div class="well-sm post-rech">
			 	<div class="row">
		 			<div class="col-md-12">
		 				<div class="row">
			 				<div class="col-md-1"> 
					 			<div style="text-align: left; margin-left: 15px">
					 				<span class="glyphicon glyphicon-circle-arrow-down red-glyph"></span>
					 			</div>
					 		</div>
						 	<div class="col-md-7">
						 		<b>Creador: </b>
						 		<% if !calif.creador %>
						 			<b>UnAventon!<span class="glyphicon glyphicon-copyright-mark"></span></b> <br>
						 		<% else %>
						 			 <%= link_to image_tag(calif.creador.avatar,:class=>"circular-image post-image", :alt=>'Avatar')+'  '+ usernameOf(calif.creador), user_path(calif.creador) %><br>
						 		<% end %>
				 			</div>
				 			<div class="col-md-4" >
				 				<div style="text-align: right; margin-right: 15px">
				 					<span class="glyphicon glyphicon-calendar"></span>  <%= '  '+formato_fecha(calif.fecha) %> <%= calif.hora.strftime('%H:%M') %><br>
				 				</div>
				 			</div>
		 				</div>
		 				<br>
			 			<div class="row" style="margin-right: 15px; margin-left:15px ">
					 			<b>Descripcion: </b><br>
					 			<div class="well my-jumbotron2">
					 				<%= calif.descripcion %>
					 			</div>
			 			</div>
		 			</div>
		 		</div>
		 	</div>
		<% else %>
		 	<div class="well-sm post-pend">
		 		<div class="row">
		 			<div class="col-md-12">
		 				<div class="row">
				 			<div class="col-md-1">
				 				<div style="text-align: left; margin-left: 15px" >
						 			<span class="glyphicon glyphicon-record blue-glyph"></span>
						 		</div>
						 	</div>
						 	<div class="col-md-8">
						 		<b>Creador: </b>
						 		<% if !calif.creador %>
						 			<b>UnAventon!<span class="glyphicon glyphicon-copyright-mark"></span></b> <br>
						 		<% else %>
						 			 <%= link_to image_tag(calif.creador.avatar,:class=>"circular-image post-image", :alt=>'Avatar')+'  '+ usernameOf(calif.creador), user_path(calif.creador) %><br>
						 		<% end %>
				 			</div>
				 			<div class="col-md-3">
				 				<div style="text-align: right; margin-right: 15px">
				 					<span class="glyphicon glyphicon-calendar"></span>  <%= '  '+formato_fecha(calif.fecha) %> <%= calif.hora.strftime('%H:%M') %><br>
				 				</div>
				 			</div>
			 			</div>
			 			<br>
			 			<div class="row" style="margin-right: 15px; margin-left:15px ">
					 			<b>Descripcion: </b><br>
					 			<div class="well my-jumbotron2">
					 				<%= calif.descripcion %>
					 			</div>
			 			</div>
		 			</div>
		 		</div>
		 	</div>
		<% end %>
		<br>
	<% end %>
	<div class="pagination-wrapper">
        <div class="pagination">
          <%= will_paginate @calif_copiloto, param_name: 'co_page',previous_label: 'Página anterior', next_label: 'Página siguiente' %>
        </div>
    </div>
<% end %>

app/views/partials/partialsUser/_mostrarPostulaciones.html.erb
<div class="col-md-10">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10" style="background-color: #fafafa">
      <h1 style="text-align: center;">
        Postulaciones en viajes activos:<br><br>
      </h1>
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <% if @postulaciones.empty? %>
            <h3 style="text-align: center;">
             No posee postulaciones a viajes activos.
            </h3>
          <% else %>
            <% @postulaciones.all.each do |pos| %>
              <% if pos.trip.activo %>
                <% if pos.estado == 'a' %>
                  <div class="well post-acept">
                    <div class="row">
                      <div class="col-md-1">
                        <span class="glyphicon glyphicon-ok-sign green-glyph" data-toggle="tooltip" title="Aceptado"></span>
                      </div>
                      <div class="col-md-8" style="font-size:18px">
                        <%= link_to pos.trip.origen+' - '+pos.trip.destino, user_trip_path(pos.trip.piloto, pos.trip) %>
                      </div>
                      <div class="col-md-3">
                        <span class="glyphicon glyphicon-calendar"></span> <%= '  '+formato_fecha(pos.trip.fecha_inicio) %>  <%= pos.trip.hora_inicio.strftime('%H:%M') %>
                      </div>
                    </div>
                  </div>
                <% elsif pos.estado == 'p' %>
                  <div class="well post-pend">
                    <div class="row">
                      <div class="col-md-1">
                        <span class="glyphicon glyphicon-time blue-glyph" data-toggle="tooltip" title="Pendiente"></span>
                      </div>
                      <div class="col-md-8" style="font-size:18px">
                        <%= link_to pos.trip.origen+' - '+pos.trip.destino, user_trip_path(pos.trip.piloto, pos.trip) %>
                      </div>
                      <div class="col-md-3">
                        <span class="glyphicon glyphicon-calendar"></span><%= '  '+formato_fecha(pos.trip.fecha_inicio) %> <%= pos.trip.hora_inicio.strftime('%H:%M') %>
                      </div>
                    </div>
                  </div>
                <% else %>
                  <div class="well-sm post-rech">
                    <div class="row">
                      <div class="col-md-1">
                        <span class="glyphicon glyphicon-remove-sign red-glyph" data-toggle="tooltip" title="Rechazado"></span>
                      </div>
                      <div class="col-md-8" style="font-size:18px">
                        <%= link_to pos.trip.origen+' - '+pos.trip.destino, user_trip_path(pos.trip.piloto, pos.trip) %>
                      </div>
                      <div class="col-md-3">
                        <span class="glyphicon glyphicon-calendar"></span> <%= '  '+formato_fecha(pos.trip.fecha_inicio) %> <%= pos.trip.hora_inicio.strftime('%H:%M') %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  </div>
</div>

app/views/partials/partialsUser/_mostrarVehiculos.html.erb
<div class="col-md-10">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10" style="background-color: #fafafa">
      <h1 style="text-align: center;">
        Vehiculos<br>
      </h1>
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <% if @user == current_user %>
            <br> <br>
            <%= link_to 'Nuevo Vehiculo', new_user_vehicle_path(@user),:class => "btn btn-block btn-lg colapso my-link-button" %>
            <br><br>
          <% end %>
        </div>
        <div class="col-md-1"></div>
      </div>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-10">
          <% if @user.vehicles.all.empty? %>
          <h3 style="text-align: center;">
            <% if @user == current_user %>
            No posee vehiculos, <%= link_to ' agrega uno!', new_user_vehicle_path(@user) %>
            <% else %>
            No posee vehiculos
            <% end %>
          </h3>
          <% else %>
            <% @vehicle.each do |ve| %>
              <div class="well my-jumbotron" >
                <h3 style="text-align: center;">
                  Patente: <%= ve.patente.upcase %>
                </h3>
                <br/>
                <div class="row ">
                  <div class="col-md-4" >
                    <div>
                      <h5 style="font-weight: bold;">
                        Marca: <%= ve.marca.upcase %>
                      </h5>
                    </div>
                    <div >
                      <h5 style="font-weight: bold;">
                        Tipo:
                        <%= ve.tipo.upcase %>
                      </h5>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div>
                      <h5 style="font-weight: bold;">
                        Modelo:
                        <%= ve.sub_marca.upcase %>
                      </h5>
                    </div>
                    <div>
                      <h5 style="font-weight: bold;">
                        Color:
                        <%= ve.color.upcase %>
                      </h5>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div>
                      <h5 style="font-weight: bold;">
                        Año:
                        <%= ve.modelo %>
                      </h5>
                    </div>
                    <div>
                      <h5 style="font-weight: bold;">
                        Asientos:
                        <%= ve.cantidad_asientos %>
                      </h5>
                    </div>
                    <br>
                  </div>
                </div>
                  <div class="row">
                  <% if @user == current_user %>
                    <div class="center" style="width: 100%; margin-bottom: 5px">
                    <b>
                      <%= link_to 'Modificar', edit_user_vehicle_path(@user,ve.id),:class => "btn btn-block btn-sm my-button-color my-link-button" %>
                    </b>
                    </div>

                    <div class="center" style="width: 100%; margin-top: 5px">
                    <b>
                      <%= link_to 'Eliminar', user_vehicle_path(@user,ve), method: :delete,:class => "btn btn-block btn-sm my-button-color my-link-button", data: {confirm: '¿Estas seguro que quieres eliminar el vehiculo?'} %>
                      </b>
                    </div>
                  <% end %>
                </div>
              </div>
              <br>
            <% end %>
            <div class="pagination-wrapper">
              <div class="pagination">
                  <%= will_paginate @vehicle, previous_label: 'Página anterior', next_label: 'Página siguiente' %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-md-1">
      </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/partialsUser/_mostrarViajes.html.erb
<div class="col-md-1">
</div>
<div class="col-md-10" style="background-color: #fafafa">
  <h1 style="text-align: center;">
	Ultimos Viajes
  </h1><br><br>
  <div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10">
	  <% if @realizado.empty? %>
		<div>
			<% if @user == current_user %>
				<h3> No has realizado viajes todavia :( </h3>		  
				<p>
					<ul> <%= link_to 'Crea un viaje', new_user_trip_path(current_user) %> </ul>
					<ul> <%= link_to 'Mira los viajes disponibles', root_path %> </ul>
				</p>
			<% else %>
				<h3> El usuario no ha realizado viajes todavia :( </h3>
		  	<% end %>
		</div>
	  <% else %>
		<% @realizado.each do |t| %>
		  <div class="well my-jumbotron">
			<div class="row">
			  <h3 style="text-align: center;">
				<%='Origen: '+t.origen %>   -    <%= 'Destino: '+t.destino %>
			  </h3>
			</div>
			<div class="row">
			  <div class="col-md-4">
				<h5>
				  <b>Fecha: </b> <%= formato_fecha(t.fecha_inicio) %>
				</h5>
				<h5>
				  <b>Hora: </b> <%= t.hora_inicio.strftime('%H:%M') %>
				</h5>
				<h5>
                      <b>Periodico: </b>
                      <% if t.periodics.any? %>
                        Si
                      <% else %>
                        No
                      <% end %>
                </h5>
				<h5>
				  <b>Piloto: </b> <%= link_to image_tag(t.piloto.avatar.url,:class=>"circular-image small-image")+'  '+usernameOf(t.piloto), user_path(t.piloto) %>
				</h5>
				<h5>
				  <b>Asientos: </b> <%= t.cantidad_asientos_ocupados %> / <%= t.vehicle.cantidad_asientos %>
				</h5>
			  </div>
			  <div class="col-md-8">
				<div class="row" style="width: 100%;">
				  <h4>
					<b>Descripcion:</b> <%= t.descripcion %>
				  </h4>
				</div>
			  </div>
			</div>
			<br>
			<div class=" row">
			  <div class="col-md-4"></div>
			  <div class="col-md-4">
				<b>
					<%= link_to 'Ver detalle', user_trip_path(t.piloto, t),:class => "btn btn-block btn-md my-button-color my-link-button"%>
				</b>
			  </div>
			  <div class="col-md-4"></div>
			</div>
		  </div>
		  <br>
		<% end %>
	  <% end %>
	</div>
  </div>
</div>
<div class="col-md-1">
</div>